In [33]:
import numpy as np
import math

In [5]:
a = np.arange(15).reshape(3, 5)

In [10]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype

dtype('int32')

In [9]:
a.dtype.name

'int32'

In [11]:
a.itemsize  # size of the each element in byte 

4

In [26]:
# b = np.array(6, 7, 8) # ValueError: only 2 non-keyword arguments accepted

b = np.array([6, 7, 8])             

b = np.array([1.2, 3, 4], dtype=int)

b = np.array([[2, 3], [4, 5]], dtype=complex)

b = np.array([[2, 3], [4, 5]], dtype=np.complex)

In [29]:
np.zeros((2, 3), np.int32)`

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [39]:
np.linspace(0, 2*math.pi, 10)

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [36]:
import math

In [38]:
math.pi

3.141592653589793

In [40]:
b<20          # compare each element 

array([[ True,  True],
       [ True,  True]])

In [41]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

A*B          # element wise multiplication 


array([[2, 0],
       [0, 4]])

In [42]:
A @ B        # matrix multiplication 

array([[5, 4],
       [3, 4]])

In [43]:
A.dot(B)    # matrix multiplication 

array([[5, 4],
       [3, 4]])

In [44]:
rg = np.random.default_rng(1)     # create instance of default random number generator

a = np.ones((2,3), dtype=int)
b = rg.random((2,3))

b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [45]:
rg.random((2,3))

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [50]:
a = np.arange(12).reshape(3,4)

In [52]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a.max()

11

In [53]:
a.min()

0

In [54]:
a.max(axis=0)                            # max value in each column

array([ 8,  9, 10, 11])

In [55]:
a.sum(axis=1)                            # sum of each row

array([ 6, 22, 38])

In [56]:
a.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [59]:
B = np.arange(3)

np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [60]:
np.sqrt(B)


array([0.        , 1.        , 1.41421356])

In [62]:
C = np.arange(3)

In [63]:
np.add(B, C)

array([0, 2, 4])