https://www.youtube.com/watch?v=69ComsKKRvA&list=PLZ7s-Z1aAtmIRpnGQGMTvV3AGdDK37d2b&index=2

In [1]:
import numpy as np 

In [2]:
np.__version__

'1.18.1'

In [3]:
my_list = [-17, 0, 4, 5, 9]

In [4]:
my_array = np.array(my_list)
my_array

array([-17,   0,   4,   5,   9])

In [5]:
type(my_array)

numpy.ndarray

In [6]:
my_array * 100

array([-1700,     0,   400,   500,   900])

In [8]:
my_tuple = (-14, -3.54, 5+7j)
np.array(my_tuple)                        # it is converted all the number to complex number 

array([-14.  +0.j,  -3.54+0.j,   5.  +7.j])

### Difference between python and numpy data structures

In [9]:
my_tuple * 6             # Python tuple replicated by 6 times

(-14,
 -3.54,
 (5+7j),
 -14,
 -3.54,
 (5+7j),
 -14,
 -3.54,
 (5+7j),
 -14,
 -3.54,
 (5+7j),
 -14,
 -3.54,
 (5+7j),
 -14,
 -3.54,
 (5+7j))

In [10]:
np.array(my_tuple) * 6          # Each element of the np array got multiplied by 6

array([-84.   +0.j, -21.24 +0.j,  30.  +42.j])

### Intrinsic Numpy array creation using Numpy's method

In [11]:
np.arange(7)                # 

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(1, 13) - 1 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
len(np.arange(1, 13))

12

In [15]:
my_range_array = np.arange(10, 23)
my_range_array.size

13

In [16]:
np.arange(10, 23).size

13

In [17]:
my_linspace = np.linspace(5, 15, 9, retstep=True)

In [18]:
my_linspace[1]

1.25

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.zeros((5, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
np.zeros(11, dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

### Slicinig 

In [26]:
my_vector = np.array([-17, 4, 0, 2, 21, 37, 105])

In [27]:
my_vector[0]

-17

In [28]:
my_vector[0] = -102

In [29]:
my_vector

array([-102,    4,    0,    2,   21,   37,  105])

In [30]:
my_vector[-3]

21

In [31]:
my_vector[305 % 7]

21

In [32]:
my_vector.size

7

In [33]:
my_vector[305 % my_vector.size]

21

## Two dimensional array

In [35]:
my_array = np.arange(35)
my_array.shape= (7, 5)

In [36]:
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [37]:
my_array[2]

array([10, 11, 12, 13, 14])

In [38]:
my_array[-2]

array([25, 26, 27, 28, 29])

In [39]:
my_array[5, 2]

27

In [40]:
row = 5
column = 2

my_array[5, 2]

27

In [41]:
my_array[5][2]

27

In [42]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2, 5, 7)
my_3D_array

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62],
        [63, 64, 65, 66, 67, 68, 69]]])

In [43]:
my_3D_array[1]


array([[35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69]])

In [44]:
my_3D_array[1, 3]

array([56, 57, 58, 59, 60, 61, 62])

In [45]:
my_3D_array[1, 3, 2]

58

In [46]:
my_3D_array[1, 3, 2] = 111

## Boolean Mask Arrays

In [47]:
zero_mod_7_mask = 0 ==(my_vector % 7)
zero_mod_7_mask

array([False, False,  True, False,  True, False,  True])

In [48]:
sub_array = my_vector[zero_mod_7_mask]

In [49]:
sub_array

array([  0,  21, 105])

In [50]:
sub_array[sub_array > 0]

array([ 21, 105])

## Numpy Logical Operators

In [51]:
mod_test = 0 == (my_vector % 7)

In [52]:
mod_test

array([False, False,  True, False,  True, False,  True])

In [55]:
positive_test = my_vector > 0

In [56]:
combined_mask = np.logical_and(mod_test, positive_test) # Numpy logical operation is faster than python

In [57]:
combined_mask

array([False, False, False, False,  True, False,  True])

In [58]:
my_vector[combined_mask]

array([ 21, 105])

## Automatic reshaping

In [63]:
a = np.arange(30)
b = a.reshape((2, -1, 3))  # -1 means "whatever is needed"
b.shape

(2, 5, 3)

## Broadcasting

In [ ]:
# One of the dimension has to be 1 
# A      (4d array):  8 x 1 x 6 x 1
# B      (3d array):      7 x 1 x 5
# Result (4d array):  8 x 7 x 6 x 5


# A      (3d array):  15 x 3 x 5
# B      (2d array):       3 x 1
# Result (3d array):  15 x 3 x 5